[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["etl"]
force_single_line = false
combine_as_imports = true
include_trailing_comma = true
multi_line_output = 3
